### ISSUE TITLE
Specify -Xmx flag

### ISSUE THREAD

**Issue by benbasson** [Fivium/DMDA#21]
Currently max heap defaults to whatever the environment default is, which appears to be an undefinable thing as per the spec (because the claim of 1/4 system RAM or 1GB whichever is smaller is clearly untrue).

Need to do some testing to see what an appropriate value is, but gut feeling from the amount of throughput and complexity is pretty low. I'd say safe in the region of 128m to 256m?

**Comment by Tatskaari** [comment]
The optimal value is dependent on load so perhaps should be configured on a deployment by deployment basis. I have made the default 256m for now which seems like a more reasonable default. As part of the installation instructions I will suggest setting these values to something sensible for the deployment.

**Comment by Tatskaari** [comment]
I have added some flags to the init script which can be seen on #23
