### ISSUE TITLE
Rotate logs using date instead of filesize

### ISSUE THREAD

**Issue by benbasson** [Fivium/DMDA#3]
It would be nicer if logs were rotated based on date. From my understanding of Log4j, this should be a simple case of constructing a DailyRollingFileAppender instead of a basic FileAppender.

**Comment by Tatskaari** [comment]
Currently the files are not rotated by dmda; the tech team is handling this with logrotate. I have added the ability to add *.xml or *.properties as the logging mode in config.xml. In this case, the logging will be configured using that file by the log4j PropertiesConfigurator or the DOMConfigurator respectively.
