### ISSUE TITLE
Ability to bind recipient email domain into insert statement

### ISSUE THREAD

**Issue by benbasson** [Fivium/DMDA#5]
The recipient email should be exposed as a bind variable for database INSERT statements so we can differentiate emails that are to different domains but stored on the same database, i.e. new.case@domain1.com, new.case@domain2.com.

**Comment by Tatskaari** [comment]
Is this not the case? The recipient bind var contains the full email address that the email was delivered to. If an email is sent to two different domains on the same database, two inserts will be created in the database. One for each domain. I can expose an extra bind var that contains just the domain without the user@ part if that is useful.

**Comment by benbasson** [comment]
Ah, ok. I thought the recipient field was sans-domain as it was with JAMES. If the full domain name is included, then we can close this issue.
