### ISSUE TITLE
Add wildcard support for matching domains

### ISSUE THREAD

**Issue by benbasson** [Fivium/DMDA#6]
i.e. match *.ecase.co.uk. or * to a certain database configuration.

**Comment by Tatskaari** [comment]
Given that we match regexps to databases and we have the following mapping:

network.rail.ecase.co.uk -> db1
hmt.ecase.co.uk -> db2
*.ecase.co.uk -> db3
*.*.co.uk -> db4

There are 2 behaviours that we could use. 
1. Work down the list of regexps and stop once one of them matched. If an email is sent to network.rail.ecase.co.uk then it will be delivered there and not to *.ecase.co.uk
2. Work through the expressions and send to all the databases associated with those that matched. network.rail.ecase.co.uk would send to db1, db3 and db4.

I assume that option 1 is preferable however I'm not sure we can guaranty the order of the element will match their position in the file when using XML. Might want to switch to a property file or include an index field in the XML file.

**Comment by AledLewis** [comment]
Personally, if it's up for a vote, I'd prefer #1. I can't think of a real-world scenario where #2 would be useful. 

If you're using either XPath or W3C Dom navigation through an XML document, order is preserved (In DOM, you can use Node::getFirstChild and Node::getNextSibling, in Xpath things are returned in the correct order for the axis used).

**Comment by Tatskaari** [comment]
Okay I will work on the assumption that 1 is what we need. I'm also wondering whether switching to property files is better anyway. Yao said that he can easily adjust the puppet script to generate them instead of XML but that's something we can change later if we want to.

**Comment by AledLewis** [comment]
It'll work as a properties file, but you'll find it tough/hacky to represent the cascading nature of the configuration in that kind of format. Hierarchical formats such as JSON/XML/YAML... fit this kind of thing better. 

Have you played with Jackson yet? That might reduce some of the sting of dealing with XML.

**Comment by benbasson** [comment]
Also voting for option 1. We don't currently have a use-case for delivering to multiple databases.

**Comment by Tatskaari** [comment]
#22
