### ISSUE TITLE
ClamAV timeout too short

### ISSUE THREAD

**Issue by Palmr** [Fivium/DMDA#9]
Currently DMDA doesn't specify a timeout when calling the ClamAV library, meaning it had a default timeout of 500ms when waiting for an OK/Virus response.

In the case of large files that are streamed to ClamAV it can take multiple seconds to fully scan before a response is sent leading to errors:

> java.net.SocketTimeoutException: Read timed out
>         at java.net.SocketInputStream.socketRead0(Native Method)
>         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
>         at java.net.SocketInputStream.read(SocketInputStream.java:170)
>         at java.net.SocketInputStream.read(SocketInputStream.java:141)
>         at java.net.SocketInputStream.read(SocketInputStream.java:127)
>         at fi.solita.clamav.ClamAVClient.readAll(ClamAVClient.java:127)
>         at fi.solita.clamav.ClamAVClient.scan(ClamAVClient.java:95)
>         at fi.solita.clamav.ClamAVClient.scan(ClamAVClient.java:106)
>         at uk.co.fivium.dmda.AntiVirus.ClamAVScanner.scan(ClamAVScanner.java:18)
>         at uk.co.fivium.dmda.AntiVirus.ClamAVScanner.checkContent(ClamAVScanner.java:29)
>         at uk.co.fivium.dmda.EmailMessages.EmailMessage.addData(EmailMessage.java:76)
>         at uk.co.fivium.dmda.EmailMessages.DatabaseMessageHandler.data(DatabaseMessageHandler.java:74)
>         at org.subethamail.smtp.command.DataCommand.execute(DataCommand.java:64)
>         at org.subethamail.smtp.server.RequireTLSCommandWrapper.execute(RequireTLSCommandWrapper.java:30)
>         at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:99)
>         at org.subethamail.smtp.server.Session.runCommandLoop(Session.java:244)
>         at org.subethamail.smtp.server.Session.run(Session.java:145)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

**Comment by Tatskaari** [comment]
You'll have to set up a configuration file to use DMDA which includes your database connection details amongst other things. 

The configuration file should be named config.xml and should go in the same folder as the jar. There's an example configuration file included in the project here:
https://github.com/Fivium/DMDA/blob/master/config.xml.sample

The timeout is set in the `<anti_virus>` element.
